# Generated by Django 2.1.4 on 2018-12-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181206_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
